{ "LINK:INTFC", 	_scpi_setLINK_INTFC, 	0 },
{ "LINK:INTFC?", 	_scpi_getLINK_INTFC, 	0 },
{ "LINK:DEVICEINFO?", 	_scpi_getLINK_DEVICEINFO, 	0 },
{ "SYSTEM:WORKMODE", 	_scpi_setSYSTEM_WORKMODE, 	0 },

{ "SYSTEM:WORKMODE?", 	_scpi_getSYSTEM_WORKMODE, 	0 },
{ "SYSTEM:POWERON", 	_scpi_setSYSTEM_POWERON, 	0 },
{ "SYSTEM:POWERON?", 	_scpi_getSYSTEM_POWERON, 	0 },
{ "SYSTEM:SN?", 	_scpi_getSYSTEM_SN, 	0 },

{ "SYSTEM:TYPE?", 	_scpi_getSYSTEM_TYPE, 	0 },
{ "SYSTEM:SOFTVER?", 	_scpi_getSYSTEM_SOFTVER, 	0 },
{ "SYSTEM:FPGAVER?", 	_scpi_getSYSTEM_FPGAVER, 	0 },
{ "SYSTEM:HARDVER?", 	_scpi_getSYSTEM_HARDVER, 	0 },

{ "SYSTEM:BOOTVER?", 	_scpi_getSYSTEM_BOOTVER, 	0 },
{ "SYSTEM:EVENTCODE?", 	_scpi_getSYSTEM_EVENTCODE, 	0 },
{ "SYSTEM:DIOSTATE?", 	_scpi_getSYSTEM_DIOSTATE, 	0 },
{ "SYSTEM:FANPARA", 	_scpi_setSYSTEM_FANPARA, 	0 },

{ "SYSTEM:FANPARA?", 	_scpi_getSYSTEM_FANPARA, 	0 },
{ "SYSTEM:ARMLEDPARA", 	_scpi_setSYSTEM_ARMLEDPARA, 	0 },
{ "SYSTEM:ARMLEDPARA?", 	_scpi_getSYSTEM_ARMLEDPARA, 	0 },
{ "RS232:BAUD", 	_scpi_setRS232_BAUD, 	0 },

{ "RS232:BAUD?", 	_scpi_getRS232_BAUD, 	0 },
{ "RS232:WORDLEN", 	_scpi_setRS232_WORDLEN, 	0 },
{ "RS232:WORDLEN?", 	_scpi_getRS232_WORDLEN, 	0 },
{ "RS232:FLOWCTL", 	_scpi_setRS232_FLOWCTL, 	0 },

{ "RS232:FLOWCTL?", 	_scpi_getRS232_FLOWCTL, 	0 },
{ "RS232:PARITY", 	_scpi_setRS232_PARITY, 	0 },
{ "RS232:PARITY?", 	_scpi_getRS232_PARITY, 	0 },
{ "RS232:STOPBIT", 	_scpi_setRS232_STOPBIT, 	0 },

{ "RS232:STOPBIT?", 	_scpi_getRS232_STOPBIT, 	0 },
{ "RS232:APPLYPARA", 	_scpi_setRS232_APPLYPARA, 	0 },
{ "CAN:TYPE", 	_scpi_setCAN_TYPE, 	0 },
{ "CAN:TYPE?", 	_scpi_getCAN_TYPE, 	0 },

{ "CAN:BAUD", 	_scpi_setCAN_BAUD, 	0 },
{ "CAN:BAUD?", 	_scpi_getCAN_BAUD, 	0 },
{ "CAN:GROUP", 	_scpi_setCAN_GROUP, 	0 },
{ "CAN:GROUP?", 	_scpi_getCAN_GROUP, 	0 },

{ "CAN:SENDID", 	_scpi_setCAN_SENDID, 	0 },
{ "CAN:SENDID?", 	_scpi_getCAN_SENDID, 	0 },
{ "CAN:RECEIVEID", 	_scpi_setCAN_RECEIVEID, 	0 },
{ "CAN:RECEIVEID?", 	_scpi_getCAN_RECEIVEID, 	0 },

{ "CAN:GROUPID1", 	_scpi_setCAN_GROUPID1, 	0 },
{ "CAN:GROUPID1?", 	_scpi_getCAN_GROUPID1, 	0 },
{ "CAN:GROUPID2", 	_scpi_setCAN_GROUPID2, 	0 },
{ "CAN:GROUPID2?", 	_scpi_getCAN_GROUPID2, 	0 },

{ "CAN:BROADCASTID", 	_scpi_setCAN_BROADCASTID, 	0 },
{ "CAN:BROADCASTID?", 	_scpi_getCAN_BROADCASTID, 	0 },
{ "CAN:APPLYPARA", 	_scpi_setCAN_APPLYPARA, 	0 },
{ "CAN:NETMANAGELED", 	_scpi_setCAN_NETMANAGELED, 	0 },

{ "CAN:NETMANAGESTATE", 	_scpi_setCAN_NETMANAGESTATE, 	0 },
{ "CAN:NETMANAGESTATE?", 	_scpi_getCAN_NETMANAGESTATE, 	0 },
{ "CAN:NETMANAGEID", 	_scpi_setCAN_NETMANAGEID, 	0 },
{ "CAN:NETMANAGEID?", 	_scpi_getCAN_NETMANAGEID, 	0 },

{ "CAN:NETMANAGEHASH", 	_scpi_setCAN_NETMANAGEHASH, 	0 },
{ "CAN:NETMANAGEHASH?", 	_scpi_getCAN_NETMANAGEHASH, 	0 },
{ "CLOCK:FREQUENCY", 	_scpi_setCLOCK_FREQUENCY, 	0 },
{ "CLOCK:FREQUENCY?", 	_scpi_getCLOCK_FREQUENCY, 	0 },

{ "CLOCK:SYNCREGISTER", 	_scpi_setCLOCK_SYNCREGISTER, 	0 },
{ "CLOCK:SYNCREGISTER?", 	_scpi_getCLOCK_SYNCREGISTER, 	0 },
{ "CLOCK:STARTTYPE", 	_scpi_setCLOCK_STARTTYPE, 	0 },
{ "CLOCK:STARTTYPE?", 	_scpi_getCLOCK_STARTTYPE, 	0 },

{ "CLOCK:SYNCSTATE", 	_scpi_setCLOCK_SYNCSTATE, 	0 },
{ "CLOCK:SYNCSTATE?", 	_scpi_getCLOCK_SYNCSTATE, 	0 },
{ "CLOCK:COUNT?", 	_scpi_getCLOCK_COUNT, 	0 },
{ "MOTION:SWITCH", 	_scpi_setMOTION_SWITCH, 	0 },

{ "MOTION:STATE?", 	_scpi_getMOTION_STATE, 	0 },
{ "MOTION:STATEREPORT", 	_scpi_setMOTION_STATEREPORT, 	0 },
{ "MOTION:STATEREPORT?", 	_scpi_getMOTION_STATEREPORT, 	0 },
{ "MOTION:STARTSOURCE", 	_scpi_setMOTION_STARTSOURCE, 	0 },

{ "MOTION:STARTSOURCE?", 	_scpi_getMOTION_STARTSOURCE, 	0 },
{ "MOTION:STARTTYPE", 	_scpi_setMOTION_STARTTYPE, 	0 },
{ "MOTION:STARTTYPE?", 	_scpi_getMOTION_STARTTYPE, 	0 },
{ "MOTION:MAXSPEED", 	_scpi_setMOTION_MAXSPEED, 	0 },

{ "MOTION:MAXSPEED?", 	_scpi_getMOTION_MAXSPEED, 	0 },
{ "MOTION:MINSPEED", 	_scpi_setMOTION_MINSPEED, 	0 },
{ "MOTION:MINSPEED?", 	_scpi_getMOTION_MINSPEED, 	0 },
{ "MOTION:MAXPOSITION", 	_scpi_setMOTION_MAXPOSITION, 	0 },

{ "MOTION:MAXPOSITION?", 	_scpi_getMOTION_MAXPOSITION, 	0 },
{ "MOTION:MINPOSITION", 	_scpi_setMOTION_MINPOSITION, 	0 },
{ "MOTION:MINPOSITION?", 	_scpi_getMOTION_MINPOSITION, 	0 },
{ "MOTION:MAXTORQUE", 	_scpi_setMOTION_MAXTORQUE, 	0 },

{ "MOTION:MAXTORQUE?", 	_scpi_getMOTION_MAXTORQUE, 	0 },
{ "MOTION:MINTORQUE", 	_scpi_setMOTION_MINTORQUE, 	0 },
{ "MOTION:MINTORQUE?", 	_scpi_getMOTION_MINTORQUE, 	0 },
{ "MOTION:MAXACCELERATION", 	_scpi_setMOTION_MAXACCELERATION, 	0 },

{ "MOTION:MAXACCELERATION?", 	_scpi_getMOTION_MAXACCELERATION, 	0 },
{ "MOTION:MINACCELERATION", 	_scpi_setMOTION_MINACCELERATION, 	0 },
{ "MOTION:MINACCELERATION?", 	_scpi_getMOTION_MINACCELERATION, 	0 },
{ "MOTION:ORIGIN", 	_scpi_setMOTION_ORIGIN, 	0 },

{ "MOTION:ORIGIN?", 	_scpi_getMOTION_ORIGIN, 	0 },
{ "MOTION:GOORIGIN", 	_scpi_setMOTION_GOORIGIN, 	0 },
{ "MOTION:OFFSETSTATE", 	_scpi_setMOTION_OFFSETSTATE, 	0 },
{ "MOTION:OFFSETSTATE?", 	_scpi_getMOTION_OFFSETSTATE, 	0 },

{ "MOTION:OFFSET", 	_scpi_setMOTION_OFFSET, 	0 },
{ "MOTION:COUNTCIRCLE?", 	_scpi_getMOTION_COUNTCIRCLE, 	0 },
{ "MOTION:ABCOUNT?", 	_scpi_getMOTION_ABCOUNT, 	0 },
{ "MOTION:REVMOTION", 	_scpi_setMOTION_REVMOTION, 	0 },

{ "MOTION:REVMOTION?", 	_scpi_getMOTION_REVMOTION, 	0 },
{ "MOTION:ABCOUNTRESET", 	_scpi_setMOTION_ABCOUNTRESET, 	0 },
{ "IDENTITY:GROUP", 	_scpi_setIDENTITY_GROUP, 	0 },
{ "IDENTITY:GROUP?", 	_scpi_getIDENTITY_GROUP, 	0 },

{ "IDENTITY:DISTDEVICE", 	_scpi_setIDENTITY_DISTDEVICE, 	0 },
{ "IDENTITY:DISTDEVICE?", 	_scpi_getIDENTITY_DISTDEVICE, 	0 },
{ "IDENTITY:LABEL", 	_scpi_setIDENTITY_LABEL, 	0 },
{ "IDENTITY:LABEL?", 	_scpi_getIDENTITY_LABEL, 	0 },

{ "MOTOR:STEPANGLE", 	_scpi_setMOTOR_STEPANGLE, 	0 },
{ "MOTOR:STEPANGLE?", 	_scpi_getMOTOR_STEPANGLE, 	0 },
{ "MOTOR:TYPE", 	_scpi_setMOTOR_TYPE, 	0 },
{ "MOTOR:TYPE?", 	_scpi_getMOTOR_TYPE, 	0 },

{ "MOTOR:POSITIONUNIT", 	_scpi_setMOTOR_POSITIONUNIT, 	0 },
{ "MOTOR:POSITIONUNIT?", 	_scpi_getMOTOR_POSITIONUNIT, 	0 },
{ "MOTOR:GEARRATIONUM", 	_scpi_setMOTOR_GEARRATIONUM, 	0 },
{ "MOTOR:GEARRATIONUM?", 	_scpi_getMOTOR_GEARRATIONUM, 	0 },

{ "MOTOR:GEARRATIODEN", 	_scpi_setMOTOR_GEARRATIODEN, 	0 },
{ "MOTOR:GEARRATIODEN?", 	_scpi_getMOTOR_GEARRATIODEN, 	0 },
{ "MOTOR:LEAD", 	_scpi_setMOTOR_LEAD, 	0 },
{ "MOTOR:LEAD?", 	_scpi_getMOTOR_LEAD, 	0 },

{ "MOTOR:PEAKSPEED", 	_scpi_setMOTOR_PEAKSPEED, 	0 },
{ "MOTOR:PEAKSPEED?", 	_scpi_getMOTOR_PEAKSPEED, 	0 },
{ "MOTOR:PEAKACCELERATION", 	_scpi_setMOTOR_PEAKACCELERATION, 	0 },
{ "MOTOR:PEAKACCELERATION?", 	_scpi_getMOTOR_PEAKACCELERATION, 	0 },

{ "MOTOR:SIZE", 	_scpi_setMOTOR_SIZE, 	0 },
{ "MOTOR:SIZE?", 	_scpi_getMOTOR_SIZE, 	0 },
{ "MOTOR:VOLTAGE", 	_scpi_setMOTOR_VOLTAGE, 	0 },
{ "MOTOR:VOLTAGE?", 	_scpi_getMOTOR_VOLTAGE, 	0 },

{ "MOTOR:CURRENT", 	_scpi_setMOTOR_CURRENT, 	0 },
{ "MOTOR:CURRENT?", 	_scpi_getMOTOR_CURRENT, 	0 },
{ "MOTOR:BACKLASH", 	_scpi_setMOTOR_BACKLASH, 	0 },
{ "MOTOR:BACKLASH?", 	_scpi_getMOTOR_BACKLASH, 	0 },

{ "ENCODER:LINENUM", 	_scpi_setENCODER_LINENUM, 	0 },
{ "ENCODER:LINENUM?", 	_scpi_getENCODER_LINENUM, 	0 },
{ "ENCODER:CHANNELNUM", 	_scpi_setENCODER_CHANNELNUM, 	0 },
{ "ENCODER:CHANNELNUM?", 	_scpi_getENCODER_CHANNELNUM, 	0 },

{ "ENCODER:TYPE", 	_scpi_setENCODER_TYPE, 	0 },
{ "ENCODER:TYPE?", 	_scpi_getENCODER_TYPE, 	0 },
{ "ENCODER:MULTIPLE", 	_scpi_setENCODER_MULTIPLE, 	0 },
{ "ENCODER:MULTIPLE?", 	_scpi_getENCODER_MULTIPLE, 	0 },

{ "ENCODER:STATE", 	_scpi_setENCODER_STATE, 	0 },
{ "ENCODER:STATE?", 	_scpi_getENCODER_STATE, 	0 },
{ "ENCODER:FEEDBACKRATIO", 	_scpi_setENCODER_FEEDBACKRATIO, 	0 },
{ "ENCODER:FEEDBACKRATIO?", 	_scpi_getENCODER_FEEDBACKRATIO, 	0 },

{ "MOTIONPLAN:PVTCONFIG", 	_scpi_setMOTIONPLAN_PVTCONFIG, 	0 },
{ "MOTIONPLAN:PVTCONFIG?", 	_scpi_getMOTIONPLAN_PVTCONFIG, 	0 },
{ "MOTIONPLAN:PRESETSTATE", 	_scpi_setMOTIONPLAN_PRESETSTATE, 	0 },
{ "MOTIONPLAN:PRESETSTATE?", 	_scpi_getMOTIONPLAN_PRESETSTATE, 	0 },

{ "MOTIONPLAN:EXECUTEMODE", 	_scpi_setMOTIONPLAN_EXECUTEMODE, 	0 },
{ "MOTIONPLAN:EXECUTEMODE?", 	_scpi_getMOTIONPLAN_EXECUTEMODE, 	0 },
{ "MOTIONPLAN:PLANMODE", 	_scpi_setMOTIONPLAN_PLANMODE, 	0 },
{ "MOTIONPLAN:PLANMODE?", 	_scpi_getMOTIONPLAN_PLANMODE, 	0 },

{ "MOTIONPLAN:MOTIONMODE", 	_scpi_setMOTIONPLAN_MOTIONMODE, 	0 },
{ "MOTIONPLAN:MOTIONMODE?", 	_scpi_getMOTIONPLAN_MOTIONMODE, 	0 },
{ "MOTIONPLAN:MODIFYDUTY", 	_scpi_setMOTIONPLAN_MODIFYDUTY, 	0 },
{ "MOTIONPLAN:MODIFYDUTY?", 	_scpi_getMOTIONPLAN_MODIFYDUTY, 	0 },

{ "MOTIONPLAN:REMAINPOINT?", 	_scpi_getMOTIONPLAN_REMAINPOINT, 	0 },
{ "MOTIONPLAN:CYCLENUM", 	_scpi_setMOTIONPLAN_CYCLENUM, 	0 },
{ "MOTIONPLAN:CYCLENUM?", 	_scpi_getMOTIONPLAN_CYCLENUM, 	0 },
{ "MOTIONPLAN:WARNPOINT", 	_scpi_setMOTIONPLAN_WARNPOINT, 	0 },

{ "MOTIONPLAN:WARNPOINT?", 	_scpi_getMOTIONPLAN_WARNPOINT, 	0 },
{ "MOTIONPLAN:ENDSTATE", 	_scpi_setMOTIONPLAN_ENDSTATE, 	0 },
{ "MOTIONPLAN:ENDSTATE?", 	_scpi_getMOTIONPLAN_ENDSTATE, 	0 },
{ "MOTIONPLAN:BUFFERSIZE?", 	_scpi_getMOTIONPLAN_BUFFERSIZE, 	0 },

{ "MOTIONPLAN:ACCSCALE", 	_scpi_setMOTIONPLAN_ACCSCALE, 	0 },
{ "MOTIONPLAN:ACCSCALE?", 	_scpi_getMOTIONPLAN_ACCSCALE, 	0 },
{ "MOTIONPLAN:DECSCALE", 	_scpi_setMOTIONPLAN_DECSCALE, 	0 },
{ "MOTIONPLAN:DECSCALE?", 	_scpi_getMOTIONPLAN_DECSCALE, 	0 },

{ "MOTIONPLAN:STOPMODE", 	_scpi_setMOTIONPLAN_STOPMODE, 	0 },
{ "MOTIONPLAN:STOPMODE?", 	_scpi_getMOTIONPLAN_STOPMODE, 	0 },
{ "MOTIONPLAN:STOPDISTANCE", 	_scpi_setMOTIONPLAN_STOPDISTANCE, 	0 },
{ "MOTIONPLAN:STOPDISTANCE?", 	_scpi_getMOTIONPLAN_STOPDISTANCE, 	0 },

{ "MOTIONPLAN:STOPTIME", 	_scpi_setMOTIONPLAN_STOPTIME, 	0 },
{ "MOTIONPLAN:STOPTIME?", 	_scpi_getMOTIONPLAN_STOPTIME, 	0 },
{ "MOTIONPLAN:OOSLINESTATE", 	_scpi_setMOTIONPLAN_OOSLINESTATE, 	0 },
{ "MOTIONPLAN:OOSLINESTATE?", 	_scpi_getMOTIONPLAN_OOSLINESTATE, 	0 },

{ "MOTIONPLAN:OOSLINEOUTNUM", 	_scpi_setMOTIONPLAN_OOSLINEOUTNUM, 	0 },
{ "MOTIONPLAN:OOSLINEOUTNUM?", 	_scpi_getMOTIONPLAN_OOSLINEOUTNUM, 	0 },
{ "MOTIONPLAN:OOSLINERESPONSE", 	_scpi_setMOTIONPLAN_OOSLINERESPONSE, 	0 },
{ "MOTIONPLAN:OOSLINERESPONSE?", 	_scpi_getMOTIONPLAN_OOSLINERESPONSE, 	0 },

{ "MOTIONPLAN:OOSTOTALSTATE", 	_scpi_setMOTIONPLAN_OOSTOTALSTATE, 	0 },
{ "MOTIONPLAN:OOSTOTALSTATE?", 	_scpi_getMOTIONPLAN_OOSTOTALSTATE, 	0 },
{ "MOTIONPLAN:OOSTOTALOUTNUM", 	_scpi_setMOTIONPLAN_OOSTOTALOUTNUM, 	0 },
{ "MOTIONPLAN:OOSTOTALOUTNUM?", 	_scpi_getMOTIONPLAN_OOSTOTALOUTNUM, 	0 },

{ "MOTIONPLAN:OOSTOTALRESPONSE", 	_scpi_setMOTIONPLAN_OOSTOTALRESPONSE, 	0 },
{ "MOTIONPLAN:OOSTOTALRESPONSE?", 	_scpi_getMOTIONPLAN_OOSTOTALRESPONSE, 	0 },
{ "POSITION:", 	_scpi_setPOSITION, 	0 },
{ "POSITION:?", 	_scpi_getPOSITION, 	0 },

{ "VELOCITY:", 	_scpi_setVELOCITY, 	0 },
{ "VELOCITY:?", 	_scpi_getVELOCITY, 	0 },
{ "TIME:", 	_scpi_setTIME, 	0 },
{ "TIME:?", 	_scpi_getTIME, 	0 },

{ "REPORT:STATE", 	_scpi_setREPORT_STATE, 	0 },
{ "REPORT:STATE?", 	_scpi_getREPORT_STATE, 	0 },
{ "REPORT:PERIOD", 	_scpi_setREPORT_PERIOD, 	0 },
{ "REPORT:PERIOD?", 	_scpi_getREPORT_PERIOD, 	0 },

{ "REPORT:DATA?", 	_scpi_getREPORT_DATA, 	0 },
{ "TRIGGER:MODE", 	_scpi_setTRIGGER_MODE, 	0 },
{ "TRIGGER:MODE?", 	_scpi_getTRIGGER_MODE, 	0 },
{ "TRIGGER:PATTSTATE", 	_scpi_setTRIGGER_PATTSTATE, 	0 },

{ "TRIGGER:PATTSTATE?", 	_scpi_getTRIGGER_PATTSTATE, 	0 },
{ "TRIGGER:PATTERN", 	_scpi_setTRIGGER_PATTERN, 	0 },
{ "TRIGGER:PATTERN?", 	_scpi_getTRIGGER_PATTERN, 	0 },
{ "TRIGGER:PATTRESP", 	_scpi_setTRIGGER_PATTRESP, 	0 },

{ "TRIGGER:PATTRESP?", 	_scpi_getTRIGGER_PATTRESP, 	0 },
{ "TRIGGER:PATTSMODE", 	_scpi_setTRIGGER_PATTSMODE, 	0 },
{ "TRIGGER:PATTSMODE?", 	_scpi_getTRIGGER_PATTSMODE, 	0 },
{ "TRIGGER:PATTSPERIOD", 	_scpi_setTRIGGER_PATTSPERIOD, 	0 },

{ "TRIGGER:PATTSPERIOD?", 	_scpi_getTRIGGER_PATTSPERIOD, 	0 },
{ "TRIGGER:LEVELSTATE", 	_scpi_setTRIGGER_LEVELSTATE, 	0 },
{ "TRIGGER:LEVELSTATE?", 	_scpi_getTRIGGER_LEVELSTATE, 	0 },
{ "TRIGGER:LEVELTYPE", 	_scpi_setTRIGGER_LEVELTYPE, 	0 },

{ "TRIGGER:LEVELTYPE?", 	_scpi_getTRIGGER_LEVELTYPE, 	0 },
{ "TRIGGER:LEVELRESP", 	_scpi_setTRIGGER_LEVELRESP, 	0 },
{ "TRIGGER:LEVELRESP?", 	_scpi_getTRIGGER_LEVELRESP, 	0 },
{ "TRIGGER:LEVELSMODE", 	_scpi_setTRIGGER_LEVELSMODE, 	0 },

{ "TRIGGER:LEVELSMODE?", 	_scpi_getTRIGGER_LEVELSMODE, 	0 },
{ "TRIGGER:LEVELSPERIOD", 	_scpi_setTRIGGER_LEVELSPERIOD, 	0 },
{ "TRIGGER:LEVELSPERIOD?", 	_scpi_getTRIGGER_LEVELSPERIOD, 	0 },
{ "DRIVER:TYPE?", 	_scpi_getDRIVER_TYPE, 	0 },

{ "DRIVER:STATEREG?", 	_scpi_getDRIVER_STATEREG, 	0 },
{ "DRIVER:CURRENT", 	_scpi_setDRIVER_CURRENT, 	0 },
{ "DRIVER:CURRENT?", 	_scpi_getDRIVER_CURRENT, 	0 },
{ "DRIVER:MICROSTEPS", 	_scpi_setDRIVER_MICROSTEPS, 	0 },

{ "DRIVER:MICROSTEPS?", 	_scpi_getDRIVER_MICROSTEPS, 	0 },
{ "DRIVER:STATE", 	_scpi_setDRIVER_STATE, 	0 },
{ "DRIVER:STATE?", 	_scpi_getDRIVER_STATE, 	0 },
{ "DRIVER:SGLIMIT", 	_scpi_setDRIVER_SGLIMIT, 	0 },

{ "DRIVER:SGLIMIT?", 	_scpi_getDRIVER_SGLIMIT, 	0 },
{ "DRIVER:SGPARASET", 	_scpi_setDRIVER_SGPARASET, 	0 },
{ "DRIVER:SGPARASET?", 	_scpi_getDRIVER_SGPARASET, 	0 },
{ "DRIVER:IDLECURRENT", 	_scpi_setDRIVER_IDLECURRENT, 	0 },

{ "DRIVER:IDLECURRENT?", 	_scpi_getDRIVER_IDLECURRENT, 	0 },
{ "DRIVER:SWITCHTIME", 	_scpi_setDRIVER_SWITCHTIME, 	0 },
{ "DRIVER:SWITCHTIME?", 	_scpi_getDRIVER_SWITCHTIME, 	0 },
{ "DRIVER:MINICURRRATIO", 	_scpi_setDRIVER_MINICURRRATIO, 	0 },

{ "DRIVER:MINICURRRATIO?", 	_scpi_getDRIVER_MINICURRRATIO, 	0 },
{ "DRIVER:REGCONFIG", 	_scpi_setDRIVER_REGCONFIG, 	0 },
{ "DRIVER:REGCONFIG?", 	_scpi_getDRIVER_REGCONFIG, 	0 },
{ "DIGITALOUTPUT:STATE", 	_scpi_setDIGITALOUTPUT_STATE, 	0 },

{ "DIGITALOUTPUT:STATE?", 	_scpi_getDIGITALOUTPUT_STATE, 	0 },
{ "DIGITALOUTPUT:SIGNAL", 	_scpi_setDIGITALOUTPUT_SIGNAL, 	0 },
{ "DIGITALOUTPUT:SIGNAL?", 	_scpi_getDIGITALOUTPUT_SIGNAL, 	0 },
{ "DIGITALOUTPUT:POLARITY", 	_scpi_setDIGITALOUTPUT_POLARITY, 	0 },

{ "DIGITALOUTPUT:POLARITY?", 	_scpi_getDIGITALOUTPUT_POLARITY, 	0 },
{ "DIGITALOUTPUT:SOURCE", 	_scpi_setDIGITALOUTPUT_SOURCE, 	0 },
{ "DIGITALOUTPUT:SOURCE?", 	_scpi_getDIGITALOUTPUT_SOURCE, 	0 },
{ "DIGITALOUTPUT:CONDITION", 	_scpi_setDIGITALOUTPUT_CONDITION, 	0 },

{ "DIGITALOUTPUT:CONDITION?", 	_scpi_getDIGITALOUTPUT_CONDITION, 	0 },
{ "DIGITALOUTPUT:PERIOD", 	_scpi_setDIGITALOUTPUT_PERIOD, 	0 },
{ "DIGITALOUTPUT:PERIOD?", 	_scpi_getDIGITALOUTPUT_PERIOD, 	0 },
{ "DIGITALOUTPUT:DUTY", 	_scpi_setDIGITALOUTPUT_DUTY, 	0 },

{ "DIGITALOUTPUT:DUTY?", 	_scpi_getDIGITALOUTPUT_DUTY, 	0 },
{ "ISOLATOROUTPUT:STATE", 	_scpi_setISOLATOROUTPUT_STATE, 	0 },
{ "ISOLATOROUTPUT:STATE?", 	_scpi_getISOLATOROUTPUT_STATE, 	0 },
{ "ISOLATOROUTPUT:SOURCE", 	_scpi_setISOLATOROUTPUT_SOURCE, 	0 },

{ "ISOLATOROUTPUT:SOURCE?", 	_scpi_getISOLATOROUTPUT_SOURCE, 	0 },
{ "ISOLATOROUTPUT:CONDITION", 	_scpi_setISOLATOROUTPUT_CONDITION, 	0 },
{ "ISOLATOROUTPUT:CONDITION?", 	_scpi_getISOLATOROUTPUT_CONDITION, 	0 },
{ "ISOLATOROUTPUT:RESPONSE", 	_scpi_setISOLATOROUTPUT_RESPONSE, 	0 },

{ "ISOLATOROUTPUT:RESPONSE?", 	_scpi_getISOLATOROUTPUT_RESPONSE, 	0 },
{ "SENSORUART:BAUD", 	_scpi_setSENSORUART_BAUD, 	0 },
{ "SENSORUART:BAUD?", 	_scpi_getSENSORUART_BAUD, 	0 },
{ "SENSORUART:WORDLEN", 	_scpi_setSENSORUART_WORDLEN, 	0 },

{ "SENSORUART:WORDLEN?", 	_scpi_getSENSORUART_WORDLEN, 	0 },
{ "SENSORUART:FLOWCTL", 	_scpi_setSENSORUART_FLOWCTL, 	0 },
{ "SENSORUART:FLOWCTL?", 	_scpi_getSENSORUART_FLOWCTL, 	0 },
{ "SENSORUART:PARITY", 	_scpi_setSENSORUART_PARITY, 	0 },

{ "SENSORUART:PARITY?", 	_scpi_getSENSORUART_PARITY, 	0 },
{ "SENSORUART:STOPBIT", 	_scpi_setSENSORUART_STOPBIT, 	0 },
{ "SENSORUART:STOPBIT?", 	_scpi_getSENSORUART_STOPBIT, 	0 },
{ "SENSORUART:APPLYPARA", 	_scpi_setSENSORUART_APPLYPARA, 	0 },

{ "SENSORUART:STATE", 	_scpi_setSENSORUART_STATE, 	0 },
{ "SENSORUART:STATE?", 	_scpi_getSENSORUART_STATE, 	0 },
{ "SENSORUART:SOF", 	_scpi_setSENSORUART_SOF, 	0 },
{ "SENSORUART:SOF?", 	_scpi_getSENSORUART_SOF, 	0 },

{ "SENSORUART:FRAMELEN", 	_scpi_setSENSORUART_FRAMELEN, 	0 },
{ "SENSORUART:FRAMELEN?", 	_scpi_getSENSORUART_FRAMELEN, 	0 },
{ "SENSORUART:RECEIVENUM", 	_scpi_setSENSORUART_RECEIVENUM, 	0 },
{ "SENSORUART:RECEIVENUM?", 	_scpi_getSENSORUART_RECEIVENUM, 	0 },

{ "SENSORUART:SWITCHTIME", 	_scpi_setSENSORUART_SWITCHTIME, 	0 },
{ "SENSORUART:SWITCHTIME?", 	_scpi_getSENSORUART_SWITCHTIME, 	0 },
{ "SENSORUART:DATA?", 	_scpi_getSENSORUART_DATA, 	0 },
{ "ISOLATORIN:STATE", 	_scpi_setISOLATORIN_STATE, 	0 },

{ "ISOLATORIN:STATE?", 	_scpi_getISOLATORIN_STATE, 	0 },
{ "ISOLATORIN:TYPE", 	_scpi_setISOLATORIN_TYPE, 	0 },
{ "ISOLATORIN:TYPE?", 	_scpi_getISOLATORIN_TYPE, 	0 },
{ "ISOLATORIN:RESPONSE", 	_scpi_setISOLATORIN_RESPONSE, 	0 },

{ "ISOLATORIN:RESPONSE?", 	_scpi_getISOLATORIN_RESPONSE, 	0 },
{ "ISOLATORIN:RESPCHAN", 	_scpi_setISOLATORIN_RESPCHAN, 	0 },
{ "ISOLATORIN:RESPCHAN?", 	_scpi_getISOLATORIN_RESPCHAN, 	0 },
{ "ISOLATORIN:SMODE", 	_scpi_setISOLATORIN_SMODE, 	0 },

{ "ISOLATORIN:SMODE?", 	_scpi_getISOLATORIN_SMODE, 	0 },
{ "ISOLATORIN:SPERIOD", 	_scpi_setISOLATORIN_SPERIOD, 	0 },
{ "ISOLATORIN:SPERIOD?", 	_scpi_getISOLATORIN_SPERIOD, 	0 },
{ "ABSENCALARM:STATE", 	_scpi_setABSENCALARM_STATE, 	0 },

{ "ABSENCALARM:STATE?", 	_scpi_getABSENCALARM_STATE, 	0 },
{ "ABSENCALARM:UPLIMIT", 	_scpi_setABSENCALARM_UPLIMIT, 	0 },
{ "ABSENCALARM:UPLIMIT?", 	_scpi_getABSENCALARM_UPLIMIT, 	0 },
{ "ABSENCALARM:DOWNLIMIT", 	_scpi_setABSENCALARM_DOWNLIMIT, 	0 },

{ "ABSENCALARM:DOWNLIMIT?", 	_scpi_getABSENCALARM_DOWNLIMIT, 	0 },
{ "ABSENCALARM:ZEROVALUE", 	_scpi_setABSENCALARM_ZEROVALUE, 	0 },
{ "ABSENCALARM:ZEROVALUE?", 	_scpi_getABSENCALARM_ZEROVALUE, 	0 },
{ "ABSENCALARM:ZEROPOSITION", 	_scpi_setABSENCALARM_ZEROPOSITION, 	0 },

{ "ABSENCALARM:ZEROPOSITION?", 	_scpi_getABSENCALARM_ZEROPOSITION, 	0 },
{ "ABSENCALARM:RESPONSE", 	_scpi_setABSENCALARM_RESPONSE, 	0 },
{ "ABSENCALARM:RESPONSE?", 	_scpi_getABSENCALARM_RESPONSE, 	0 },
{ "DISTANCEALARM:STATE", 	_scpi_setDISTANCEALARM_STATE, 	0 },

{ "DISTANCEALARM:STATE?", 	_scpi_getDISTANCEALARM_STATE, 	0 },
{ "DISTANCEALARM:ALARM1DIST", 	_scpi_setDISTANCEALARM_ALARM1DIST, 	0 },
{ "DISTANCEALARM:ALARM1DIST?", 	_scpi_getDISTANCEALARM_ALARM1DIST, 	0 },
{ "DISTANCEALARM:ALARM2DIST", 	_scpi_setDISTANCEALARM_ALARM2DIST, 	0 },

{ "DISTANCEALARM:ALARM2DIST?", 	_scpi_getDISTANCEALARM_ALARM2DIST, 	0 },
{ "DISTANCEALARM:ALARM3DIST", 	_scpi_setDISTANCEALARM_ALARM3DIST, 	0 },
{ "DISTANCEALARM:ALARM3DIST?", 	_scpi_getDISTANCEALARM_ALARM3DIST, 	0 },
{ "OTP:STATE", 	_scpi_setOTP_STATE, 	0 },

{ "OTP:STATE?", 	_scpi_getOTP_STATE, 	0 },
{ "OTP:THRESHOLD", 	_scpi_setOTP_THRESHOLD, 	0 },
{ "OTP:THRESHOLD?", 	_scpi_getOTP_THRESHOLD, 	0 },
{ "OTP:RESPONSE", 	_scpi_setOTP_RESPONSE, 	0 },

{ "OTP:RESPONSE?", 	_scpi_getOTP_RESPONSE, 	0 },
{ "OTP:PERIOD", 	_scpi_setOTP_PERIOD, 	0 },
{ "OTP:PERIOD?", 	_scpi_getOTP_PERIOD, 	0 },
{ "OTP:DATA?", 	_scpi_getOTP_DATA, 	0 },

{ "ANALOGIN:STATE", 	_scpi_setANALOGIN_STATE, 	0 },
{ "ANALOGIN:STATE?", 	_scpi_getANALOGIN_STATE, 	0 },
{ "ANALOGIN:THRESHOLDH", 	_scpi_setANALOGIN_THRESHOLDH, 	0 },
{ "ANALOGIN:THRESHOLDH?", 	_scpi_getANALOGIN_THRESHOLDH, 	0 },

{ "ANALOGIN:THRESHOLDL", 	_scpi_setANALOGIN_THRESHOLDL, 	0 },
{ "ANALOGIN:THRESHOLDL?", 	_scpi_getANALOGIN_THRESHOLDL, 	0 },
{ "ANALOGIN:RESPONSEH", 	_scpi_setANALOGIN_RESPONSEH, 	0 },
{ "ANALOGIN:RESPONSEH?", 	_scpi_getANALOGIN_RESPONSEH, 	0 },

{ "ANALOGIN:RESPONSEL", 	_scpi_setANALOGIN_RESPONSEL, 	0 },
{ "ANALOGIN:RESPONSEL?", 	_scpi_getANALOGIN_RESPONSEL, 	0 },
