{ "LINK:INTFC", 	_scpi_setLINK_INTFC, 	0 },
{ "LINK:INTFC?", 	_scpi_getLINK_INTFC, 	0 },
{ "SYSTEM:WORKMODE", 	_scpi_setSYSTEM_WORKMODE, 	0 },
{ "SYSTEM:WORKMODE?", 	_scpi_getSYSTEM_WORKMODE, 	0 },

{ "SYSTEM:POWERON", 	_scpi_setSYSTEM_POWERON, 	0 },
{ "SYSTEM:POWERON?", 	_scpi_getSYSTEM_POWERON, 	0 },
{ "SYSTEM:SN?", 	_scpi_getSYSTEM_SN, 	0 },
{ "SYSTEM:TYPE?", 	_scpi_getSYSTEM_TYPE, 	0 },

{ "SYSTEM:SOFTVER?", 	_scpi_getSYSTEM_SOFTVER, 	0 },
{ "SYSTEM:FPGAVER?", 	_scpi_getSYSTEM_FPGAVER, 	0 },
{ "SYSTEM:HARDVER?", 	_scpi_getSYSTEM_HARDVER, 	0 },
{ "SYSTEM:BOOTVER?", 	_scpi_getSYSTEM_BOOTVER, 	0 },

{ "SYSTEM:ERROR?", 	_scpi_getSYSTEM_ERROR, 	0 },
{ "SYSTEM:REPORTSWITCH", 	_scpi_setSYSTEM_REPORTSWITCH, 	0 },
{ "SYSTEM:REPORTSWITCH?", 	_scpi_getSYSTEM_REPORTSWITCH, 	0 },
{ "RS232:BAUD", 	_scpi_setRS232_BAUD, 	0 },

{ "RS232:BAUD?", 	_scpi_getRS232_BAUD, 	0 },
{ "RS232:WORDLEN", 	_scpi_setRS232_WORDLEN, 	0 },
{ "RS232:WORDLEN?", 	_scpi_getRS232_WORDLEN, 	0 },
{ "RS232:FLOWCTL", 	_scpi_setRS232_FLOWCTL, 	0 },

{ "RS232:FLOWCTL?", 	_scpi_getRS232_FLOWCTL, 	0 },
{ "RS232:PARITY", 	_scpi_setRS232_PARITY, 	0 },
{ "RS232:PARITY?", 	_scpi_getRS232_PARITY, 	0 },
{ "RS232:STOPBIT", 	_scpi_setRS232_STOPBIT, 	0 },

{ "RS232:STOPBIT?", 	_scpi_getRS232_STOPBIT, 	0 },
{ "RS232:APPLYPARA", 	_scpi_setRS232_APPLYPARA, 	0 },
{ "CAN:TYPE", 	_scpi_setCAN_TYPE, 	0 },
{ "CAN:TYPE?", 	_scpi_getCAN_TYPE, 	0 },

{ "CAN:BAUD", 	_scpi_setCAN_BAUD, 	0 },
{ "CAN:BAUD?", 	_scpi_getCAN_BAUD, 	0 },
{ "CAN:GROUP", 	_scpi_setCAN_GROUP, 	0 },
{ "CAN:GROUP?", 	_scpi_getCAN_GROUP, 	0 },

{ "CAN:SENDID", 	_scpi_setCAN_SENDID, 	0 },
{ "CAN:SENDID?", 	_scpi_getCAN_SENDID, 	0 },
{ "CAN:RECEIVEID", 	_scpi_setCAN_RECEIVEID, 	0 },
{ "CAN:RECEIVEID?", 	_scpi_getCAN_RECEIVEID, 	0 },

{ "CAN:GROUPID1", 	_scpi_setCAN_GROUPID1, 	0 },
{ "CAN:GROUPID1?", 	_scpi_getCAN_GROUPID1, 	0 },
{ "CAN:GROUPID2", 	_scpi_setCAN_GROUPID2, 	0 },
{ "CAN:GROUPID2?", 	_scpi_getCAN_GROUPID2, 	0 },

{ "CAN:BROADCASTID", 	_scpi_setCAN_BROADCASTID, 	0 },
{ "CAN:BROADCASTID?", 	_scpi_getCAN_BROADCASTID, 	0 },
{ "CAN:APPLYPARA", 	_scpi_setCAN_APPLYPARA, 	0 },
{ "CAN:NETMANAGELED", 	_scpi_setCAN_NETMANAGELED, 	0 },

{ "CAN:NETMANAGESTATE", 	_scpi_setCAN_NETMANAGESTATE, 	0 },
{ "CAN:NETMANAGESTATE?", 	_scpi_getCAN_NETMANAGESTATE, 	0 },
{ "CAN:NETMANAGEID", 	_scpi_setCAN_NETMANAGEID, 	0 },
{ "CAN:NETMANAGEID?", 	_scpi_getCAN_NETMANAGEID, 	0 },

{ "CAN:NETMANAGEHASH", 	_scpi_setCAN_NETMANAGEHASH, 	0 },
{ "CAN:NETMANAGEHASH?", 	_scpi_getCAN_NETMANAGEHASH, 	0 },
{ "CLOCK:FREQUENCY", 	_scpi_setCLOCK_FREQUENCY, 	0 },
{ "CLOCK:FREQUENCY?", 	_scpi_getCLOCK_FREQUENCY, 	0 },

{ "CLOCK:SYNCREGISTER", 	_scpi_setCLOCK_SYNCREGISTER, 	0 },
{ "CLOCK:SYNCREGISTER?", 	_scpi_getCLOCK_SYNCREGISTER, 	0 },
{ "CLOCK:STARTTYPE", 	_scpi_setCLOCK_STARTTYPE, 	0 },
{ "CLOCK:STARTTYPE?", 	_scpi_getCLOCK_STARTTYPE, 	0 },

{ "CLOCK:SYNCSTATE", 	_scpi_setCLOCK_SYNCSTATE, 	0 },
{ "CLOCK:SYNCSTATE?", 	_scpi_getCLOCK_SYNCSTATE, 	0 },
{ "CLOCK:COUNT?", 	_scpi_getCLOCK_COUNT, 	0 },
{ "MOTION:SWITCH", 	_scpi_setMOTION_SWITCH, 	0 },

{ "MOTION:STATE?", 	_scpi_getMOTION_STATE, 	0 },
{ "MOTION:STATEREPORT", 	_scpi_setMOTION_STATEREPORT, 	0 },
{ "MOTION:STATEREPORT?", 	_scpi_getMOTION_STATEREPORT, 	0 },
{ "MOTION:STARTSOURCE", 	_scpi_setMOTION_STARTSOURCE, 	0 },

{ "MOTION:STARTSOURCE?", 	_scpi_getMOTION_STARTSOURCE, 	0 },
{ "MOTION:STARTTYPE", 	_scpi_setMOTION_STARTTYPE, 	0 },
{ "MOTION:STARTTYPE?", 	_scpi_getMOTION_STARTTYPE, 	0 },
{ "MOTION:MAXSPEED", 	_scpi_setMOTION_MAXSPEED, 	0 },

{ "MOTION:MAXSPEED?", 	_scpi_getMOTION_MAXSPEED, 	0 },
{ "MOTION:MINSPEED", 	_scpi_setMOTION_MINSPEED, 	0 },
{ "MOTION:MINSPEED?", 	_scpi_getMOTION_MINSPEED, 	0 },
{ "MOTION:MAXPOSITION", 	_scpi_setMOTION_MAXPOSITION, 	0 },

{ "MOTION:MAXPOSITION?", 	_scpi_getMOTION_MAXPOSITION, 	0 },
{ "MOTION:MINPOSITION", 	_scpi_setMOTION_MINPOSITION, 	0 },
{ "MOTION:MINPOSITION?", 	_scpi_getMOTION_MINPOSITION, 	0 },
{ "MOTION:MAXTORQUE", 	_scpi_setMOTION_MAXTORQUE, 	0 },

{ "MOTION:MAXTORQUE?", 	_scpi_getMOTION_MAXTORQUE, 	0 },
{ "MOTION:MINTORQUE", 	_scpi_setMOTION_MINTORQUE, 	0 },
{ "MOTION:MINTORQUE?", 	_scpi_getMOTION_MINTORQUE, 	0 },
{ "MOTION:MAXACCELERATION", 	_scpi_setMOTION_MAXACCELERATION, 	0 },

{ "MOTION:MAXACCELERATION?", 	_scpi_getMOTION_MAXACCELERATION, 	0 },
{ "MOTION:MINACCELERATION", 	_scpi_setMOTION_MINACCELERATION, 	0 },
{ "MOTION:MINACCELERATION?", 	_scpi_getMOTION_MINACCELERATION, 	0 },
{ "MOTION:ORIGIN", 	_scpi_setMOTION_ORIGIN, 	0 },

{ "MOTION:ORIGIN?", 	_scpi_getMOTION_ORIGIN, 	0 },
{ "MOTION:GOORIGIN", 	_scpi_setMOTION_GOORIGIN, 	0 },
{ "MOTION:INITPOSITIONUNIT", 	_scpi_setMOTION_INITPOSITIONUNIT, 	0 },
{ "MOTION:INITPOSITIONUNIT?", 	_scpi_getMOTION_INITPOSITIONUNIT, 	0 },

{ "MOTION:INITPOSITION", 	_scpi_setMOTION_INITPOSITION, 	0 },
{ "MOTION:INITPOSITION?", 	_scpi_getMOTION_INITPOSITION, 	0 },
{ "MOTION:INITIOSIGNAL", 	_scpi_setMOTION_INITIOSIGNAL, 	0 },
{ "MOTION:INITIOSIGNAL?", 	_scpi_getMOTION_INITIOSIGNAL, 	0 },

{ "MOTION:GOINITPOSITION", 	_scpi_setMOTION_GOINITPOSITION, 	0 },
{ "MOTION:INCHINGMODE", 	_scpi_setMOTION_INCHINGMODE, 	0 },
{ "MOTION:INCHINGMODE?", 	_scpi_getMOTION_INCHINGMODE, 	0 },
{ "MOTION:INCHINGTIME", 	_scpi_setMOTION_INCHINGTIME, 	0 },

{ "MOTION:INCHINGTIME?", 	_scpi_getMOTION_INCHINGTIME, 	0 },
{ "MOTION:INCHING", 	_scpi_setMOTION_INCHING, 	0 },
{ "MOTION:OFFSETSTATE", 	_scpi_setMOTION_OFFSETSTATE, 	0 },
{ "MOTION:OFFSETSTATE?", 	_scpi_getMOTION_OFFSETSTATE, 	0 },

{ "MOTION:OFFSET", 	_scpi_setMOTION_OFFSET, 	0 },
{ "MOTION:PVTSTEPS?", 	_scpi_getMOTION_PVTSTEPS, 	0 },
{ "MOTION:COUNTSTEPS?", 	_scpi_getMOTION_COUNTSTEPS, 	0 },
{ "MOTION:PVTCIRCLE?", 	_scpi_getMOTION_PVTCIRCLE, 	0 },

{ "MOTION:COUNTCIRCLE?", 	_scpi_getMOTION_COUNTCIRCLE, 	0 },
{ "MOTION:ABCOUNT?", 	_scpi_getMOTION_ABCOUNT, 	0 },
{ "MOTION:REVMOTION", 	_scpi_setMOTION_REVMOTION, 	0 },
{ "MOTION:REVMOTION?", 	_scpi_getMOTION_REVMOTION, 	0 },

{ "IDENTITY:GROUP", 	_scpi_setIDENTITY_GROUP, 	0 },
{ "IDENTITY:GROUP?", 	_scpi_getIDENTITY_GROUP, 	0 },
{ "IDENTITY:DISTDEVICE", 	_scpi_setIDENTITY_DISTDEVICE, 	0 },
{ "IDENTITY:DISTDEVICE?", 	_scpi_getIDENTITY_DISTDEVICE, 	0 },

{ "STOPDECEL:MODE", 	_scpi_setSTOPDECEL_MODE, 	0 },
{ "STOPDECEL:MODE?", 	_scpi_getSTOPDECEL_MODE, 	0 },
{ "STOPDECEL:DISTANCE", 	_scpi_setSTOPDECEL_DISTANCE, 	0 },
{ "STOPDECEL:DISTANCE?", 	_scpi_getSTOPDECEL_DISTANCE, 	0 },

{ "STOPDECEL:TIME", 	_scpi_setSTOPDECEL_TIME, 	0 },
{ "STOPDECEL:TIME?", 	_scpi_getSTOPDECEL_TIME, 	0 },
{ "OUTOFSTEP:LINESTATE", 	_scpi_setOUTOFSTEP_LINESTATE, 	0 },
{ "OUTOFSTEP:LINESTATE?", 	_scpi_getOUTOFSTEP_LINESTATE, 	0 },

{ "OUTOFSTEP:LINEOUTNUM", 	_scpi_setOUTOFSTEP_LINEOUTNUM, 	0 },
{ "OUTOFSTEP:LINEOUTNUM?", 	_scpi_getOUTOFSTEP_LINEOUTNUM, 	0 },
{ "OUTOFSTEP:LINERESPONSE", 	_scpi_setOUTOFSTEP_LINERESPONSE, 	0 },
{ "OUTOFSTEP:LINERESPONSE?", 	_scpi_getOUTOFSTEP_LINERESPONSE, 	0 },

{ "OUTOFSTEP:LINEWARN", 	_scpi_setOUTOFSTEP_LINEWARN, 	0 },
{ "OUTOFSTEP:TOTALSTATE", 	_scpi_setOUTOFSTEP_TOTALSTATE, 	0 },
{ "OUTOFSTEP:TOTALSTATE?", 	_scpi_getOUTOFSTEP_TOTALSTATE, 	0 },
{ "OUTOFSTEP:TOTALOUTNUM", 	_scpi_setOUTOFSTEP_TOTALOUTNUM, 	0 },

{ "OUTOFSTEP:TOTALOUTNUM?", 	_scpi_getOUTOFSTEP_TOTALOUTNUM, 	0 },
{ "OUTOFSTEP:TOTALRESPONSE", 	_scpi_setOUTOFSTEP_TOTALRESPONSE, 	0 },
{ "OUTOFSTEP:TOTALRESPONSE?", 	_scpi_getOUTOFSTEP_TOTALRESPONSE, 	0 },
{ "OUTOFSTEP:TOTALWARN", 	_scpi_setOUTOFSTEP_TOTALWARN, 	0 },

{ "MOTOR:STEPANGLE", 	_scpi_setMOTOR_STEPANGLE, 	0 },
{ "MOTOR:STEPANGLE?", 	_scpi_getMOTOR_STEPANGLE, 	0 },
{ "MOTOR:TYPE", 	_scpi_setMOTOR_TYPE, 	0 },
{ "MOTOR:TYPE?", 	_scpi_getMOTOR_TYPE, 	0 },

{ "MOTOR:POSITIONUNIT", 	_scpi_setMOTOR_POSITIONUNIT, 	0 },
{ "MOTOR:POSITIONUNIT?", 	_scpi_getMOTOR_POSITIONUNIT, 	0 },
{ "MOTOR:GEARRATIONUM", 	_scpi_setMOTOR_GEARRATIONUM, 	0 },
{ "MOTOR:GEARRATIONUM?", 	_scpi_getMOTOR_GEARRATIONUM, 	0 },

{ "MOTOR:GEARRATIODEN", 	_scpi_setMOTOR_GEARRATIODEN, 	0 },
{ "MOTOR:GEARRATIODEN?", 	_scpi_getMOTOR_GEARRATIODEN, 	0 },
{ "MOTOR:LEAD", 	_scpi_setMOTOR_LEAD, 	0 },
{ "MOTOR:LEAD?", 	_scpi_getMOTOR_LEAD, 	0 },

{ "MOTOR:PEAKSPEED", 	_scpi_setMOTOR_PEAKSPEED, 	0 },
{ "MOTOR:PEAKSPEED?", 	_scpi_getMOTOR_PEAKSPEED, 	0 },
{ "MOTOR:PEAKACCELERATION", 	_scpi_setMOTOR_PEAKACCELERATION, 	0 },
{ "MOTOR:PEAKACCELERATION?", 	_scpi_getMOTOR_PEAKACCELERATION, 	0 },

{ "MOTOR:SIZE", 	_scpi_setMOTOR_SIZE, 	0 },
{ "MOTOR:SIZE?", 	_scpi_getMOTOR_SIZE, 	0 },
{ "MOTOR:VOLTAGE", 	_scpi_setMOTOR_VOLTAGE, 	0 },
{ "MOTOR:VOLTAGE?", 	_scpi_getMOTOR_VOLTAGE, 	0 },

{ "MOTOR:CURRENT", 	_scpi_setMOTOR_CURRENT, 	0 },
{ "MOTOR:CURRENT?", 	_scpi_getMOTOR_CURRENT, 	0 },
{ "MOTOR:BACKLASH", 	_scpi_setMOTOR_BACKLASH, 	0 },
{ "MOTOR:BACKLASH?", 	_scpi_getMOTOR_BACKLASH, 	0 },

{ "ENCODER:LINENUM", 	_scpi_setENCODER_LINENUM, 	0 },
{ "ENCODER:LINENUM?", 	_scpi_getENCODER_LINENUM, 	0 },
{ "ENCODER:CHANNELNUM", 	_scpi_setENCODER_CHANNELNUM, 	0 },
{ "ENCODER:CHANNELNUM?", 	_scpi_getENCODER_CHANNELNUM, 	0 },

{ "ENCODER:TYPE", 	_scpi_setENCODER_TYPE, 	0 },
{ "ENCODER:TYPE?", 	_scpi_getENCODER_TYPE, 	0 },
{ "ENCODER:MULTIPLE", 	_scpi_setENCODER_MULTIPLE, 	0 },
{ "ENCODER:MULTIPLE?", 	_scpi_getENCODER_MULTIPLE, 	0 },

{ "ENCODER:STATE", 	_scpi_setENCODER_STATE, 	0 },
{ "ENCODER:STATE?", 	_scpi_getENCODER_STATE, 	0 },
{ "MOTIONPLAN:PVTCONFIG", 	_scpi_setMOTIONPLAN_PVTCONFIG, 	0 },
{ "MOTIONPLAN:PVTCONFIG?", 	_scpi_getMOTIONPLAN_PVTCONFIG, 	0 },

{ "MOTIONPLAN:POSITION", 	_scpi_setMOTIONPLAN_POSITION, 	0 },
{ "MOTIONPLAN:POSITION?", 	_scpi_getMOTIONPLAN_POSITION, 	0 },
{ "MOTIONPLAN:VELOCITY", 	_scpi_setMOTIONPLAN_VELOCITY, 	0 },
{ "MOTIONPLAN:VELOCITY?", 	_scpi_getMOTIONPLAN_VELOCITY, 	0 },

{ "MOTIONPLAN:TIME", 	_scpi_setMOTIONPLAN_TIME, 	0 },
{ "MOTIONPLAN:TIME?", 	_scpi_getMOTIONPLAN_TIME, 	0 },
{ "MOTIONPLAN:EXECUTEMODE", 	_scpi_setMOTIONPLAN_EXECUTEMODE, 	0 },
{ "MOTIONPLAN:EXECUTEMODE?", 	_scpi_getMOTIONPLAN_EXECUTEMODE, 	0 },

{ "MOTIONPLAN:PLANMODE", 	_scpi_setMOTIONPLAN_PLANMODE, 	0 },
{ "MOTIONPLAN:PLANMODE?", 	_scpi_getMOTIONPLAN_PLANMODE, 	0 },
{ "MOTIONPLAN:MOTIONMODE", 	_scpi_setMOTIONPLAN_MOTIONMODE, 	0 },
{ "MOTIONPLAN:MOTIONMODE?", 	_scpi_getMOTIONPLAN_MOTIONMODE, 	0 },

{ "MOTIONPLAN:MODIFYDUTY", 	_scpi_setMOTIONPLAN_MODIFYDUTY, 	0 },
{ "MOTIONPLAN:MODIFYDUTY?", 	_scpi_getMOTIONPLAN_MODIFYDUTY, 	0 },
{ "MOTIONPLAN:REMAINPOINT?", 	_scpi_getMOTIONPLAN_REMAINPOINT, 	0 },
{ "MOTIONPLAN:OUTPUTPOINT?", 	_scpi_getMOTIONPLAN_OUTPUTPOINT, 	0 },

{ "MOTIONPLAN:STARTPOINT", 	_scpi_setMOTIONPLAN_STARTPOINT, 	0 },
{ "MOTIONPLAN:STARTPOINT?", 	_scpi_getMOTIONPLAN_STARTPOINT, 	0 },
{ "MOTIONPLAN:ENDPOINT", 	_scpi_setMOTIONPLAN_ENDPOINT, 	0 },
{ "MOTIONPLAN:ENDPOINT?", 	_scpi_getMOTIONPLAN_ENDPOINT, 	0 },

{ "MOTIONPLAN:CYCLENUM", 	_scpi_setMOTIONPLAN_CYCLENUM, 	0 },
{ "MOTIONPLAN:CYCLENUM?", 	_scpi_getMOTIONPLAN_CYCLENUM, 	0 },
{ "MOTIONPLAN:WARNPOINT", 	_scpi_setMOTIONPLAN_WARNPOINT, 	0 },
{ "MOTIONPLAN:WARNPOINT?", 	_scpi_getMOTIONPLAN_WARNPOINT, 	0 },

{ "MOTIONPLAN:WARN", 	_scpi_setMOTIONPLAN_WARN, 	0 },
{ "MOTIONPLAN:ENDSTATE", 	_scpi_setMOTIONPLAN_ENDSTATE, 	0 },
{ "MOTIONPLAN:ENDSTATE?", 	_scpi_getMOTIONPLAN_ENDSTATE, 	0 },
{ "MOTIONPLAN:FEEDBACKRATIO", 	_scpi_setMOTIONPLAN_FEEDBACKRATIO, 	0 },

{ "MOTIONPLAN:FEEDBACKRATIO?", 	_scpi_getMOTIONPLAN_FEEDBACKRATIO, 	0 },
{ "REPORT:STATE", 	_scpi_setREPORT_STATE, 	0 },
{ "REPORT:STATE?", 	_scpi_getREPORT_STATE, 	0 },
{ "REPORT:PERIOD", 	_scpi_setREPORT_PERIOD, 	0 },

{ "REPORT:PERIOD?", 	_scpi_getREPORT_PERIOD, 	0 },
{ "REPORT:DATA?", 	_scpi_getREPORT_DATA, 	0 },
{ "TRIGGER:MODE", 	_scpi_setTRIGGER_MODE, 	0 },
{ "TRIGGER:MODE?", 	_scpi_getTRIGGER_MODE, 	0 },

{ "TRIGGER:PATTSTATE", 	_scpi_setTRIGGER_PATTSTATE, 	0 },
{ "TRIGGER:PATTSTATE?", 	_scpi_getTRIGGER_PATTSTATE, 	0 },
{ "TRIGGER:PATTERN", 	_scpi_setTRIGGER_PATTERN, 	0 },
{ "TRIGGER:PATTERN?", 	_scpi_getTRIGGER_PATTERN, 	0 },

{ "TRIGGER:PATTRESP", 	_scpi_setTRIGGER_PATTRESP, 	0 },
{ "TRIGGER:PATTRESP?", 	_scpi_getTRIGGER_PATTRESP, 	0 },
{ "TRIGGER:PATTSMODE", 	_scpi_setTRIGGER_PATTSMODE, 	0 },
{ "TRIGGER:PATTSMODE?", 	_scpi_getTRIGGER_PATTSMODE, 	0 },

{ "TRIGGER:PATTSPERIOD", 	_scpi_setTRIGGER_PATTSPERIOD, 	0 },
{ "TRIGGER:PATTSPERIOD?", 	_scpi_getTRIGGER_PATTSPERIOD, 	0 },
{ "TRIGGER:LEVELSTATE", 	_scpi_setTRIGGER_LEVELSTATE, 	0 },
{ "TRIGGER:LEVELSTATE?", 	_scpi_getTRIGGER_LEVELSTATE, 	0 },

{ "TRIGGER:LEVELTYPE", 	_scpi_setTRIGGER_LEVELTYPE, 	0 },
{ "TRIGGER:LEVELTYPE?", 	_scpi_getTRIGGER_LEVELTYPE, 	0 },
{ "TRIGGER:LEVELRESP", 	_scpi_setTRIGGER_LEVELRESP, 	0 },
{ "TRIGGER:LEVELRESP?", 	_scpi_getTRIGGER_LEVELRESP, 	0 },

{ "TRIGGER:LEVELSMODE", 	_scpi_setTRIGGER_LEVELSMODE, 	0 },
{ "TRIGGER:LEVELSMODE?", 	_scpi_getTRIGGER_LEVELSMODE, 	0 },
{ "TRIGGER:LEVELSPERIOD", 	_scpi_setTRIGGER_LEVELSPERIOD, 	0 },
{ "TRIGGER:LEVELSPERIOD?", 	_scpi_getTRIGGER_LEVELSPERIOD, 	0 },

{ "DRIVER:TYPE?", 	_scpi_getDRIVER_TYPE, 	0 },
{ "DRIVER:STATEREG?", 	_scpi_getDRIVER_STATEREG, 	0 },
{ "DRIVER:CURRENT", 	_scpi_setDRIVER_CURRENT, 	0 },
{ "DRIVER:CURRENT?", 	_scpi_getDRIVER_CURRENT, 	0 },

{ "DRIVER:MICROSTEPS", 	_scpi_setDRIVER_MICROSTEPS, 	0 },
{ "DRIVER:MICROSTEPS?", 	_scpi_getDRIVER_MICROSTEPS, 	0 },
{ "DRIVER:SWITCH", 	_scpi_setDRIVER_SWITCH, 	0 },
{ "DRIVER:SWITCH?", 	_scpi_getDRIVER_SWITCH, 	0 },

{ "DRIVER:REGCONFIG", 	_scpi_setDRIVER_REGCONFIG, 	0 },
{ "DRIVER:REGCONFIG?", 	_scpi_getDRIVER_REGCONFIG, 	0 },
{ "DRIVER:SGLIMIT", 	_scpi_setDRIVER_SGLIMIT, 	0 },
{ "DRIVER:SGLIMIT?", 	_scpi_getDRIVER_SGLIMIT, 	0 },

{ "DRIVER:SGPARASET", 	_scpi_setDRIVER_SGPARASET, 	0 },
{ "DRIVER:SGPARASET?", 	_scpi_getDRIVER_SGPARASET, 	0 },
{ "DIGITALOUT:STATE", 	_scpi_setDIGITALOUT_STATE, 	0 },
{ "DIGITALOUT:STATE?", 	_scpi_getDIGITALOUT_STATE, 	0 },

{ "DIGITALOUT:SIGNAL", 	_scpi_setDIGITALOUT_SIGNAL, 	0 },
{ "DIGITALOUT:SIGNAL?", 	_scpi_getDIGITALOUT_SIGNAL, 	0 },
{ "DIGITALOUT:POLARITY", 	_scpi_setDIGITALOUT_POLARITY, 	0 },
{ "DIGITALOUT:POLARITY?", 	_scpi_getDIGITALOUT_POLARITY, 	0 },

{ "DIGITALOUT:SOURCE", 	_scpi_setDIGITALOUT_SOURCE, 	0 },
{ "DIGITALOUT:SOURCE?", 	_scpi_getDIGITALOUT_SOURCE, 	0 },
{ "DIGITALOUT:CONDITION", 	_scpi_setDIGITALOUT_CONDITION, 	0 },
{ "DIGITALOUT:CONDITION?", 	_scpi_getDIGITALOUT_CONDITION, 	0 },

{ "DIGITALOUT:PERIOD", 	_scpi_setDIGITALOUT_PERIOD, 	0 },
{ "DIGITALOUT:PERIOD?", 	_scpi_getDIGITALOUT_PERIOD, 	0 },
{ "DIGITALOUT:DUTY", 	_scpi_setDIGITALOUT_DUTY, 	0 },
{ "DIGITALOUT:DUTY?", 	_scpi_getDIGITALOUT_DUTY, 	0 },

{ "ISOLATOROUTPUT:STATE", 	_scpi_setISOLATOROUTPUT_STATE, 	0 },
{ "ISOLATOROUTPUT:STATE?", 	_scpi_getISOLATOROUTPUT_STATE, 	0 },
{ "ISOLATOROUTPUT:SOURCE", 	_scpi_setISOLATOROUTPUT_SOURCE, 	0 },
{ "ISOLATOROUTPUT:SOURCE?", 	_scpi_getISOLATOROUTPUT_SOURCE, 	0 },

{ "ISOLATOROUTPUT:CONDITION", 	_scpi_setISOLATOROUTPUT_CONDITION, 	0 },
{ "ISOLATOROUTPUT:CONDITION?", 	_scpi_getISOLATOROUTPUT_CONDITION, 	0 },
{ "ISOLATOROUTPUT:RESPONSE", 	_scpi_setISOLATOROUTPUT_RESPONSE, 	0 },
{ "ISOLATOROUTPUT:RESPONSE?", 	_scpi_getISOLATOROUTPUT_RESPONSE, 	0 },

{ "SENSORUART:BAUD", 	_scpi_setSENSORUART_BAUD, 	0 },
{ "SENSORUART:BAUD?", 	_scpi_getSENSORUART_BAUD, 	0 },
{ "SENSORUART:WORDLEN", 	_scpi_setSENSORUART_WORDLEN, 	0 },
{ "SENSORUART:WORDLEN?", 	_scpi_getSENSORUART_WORDLEN, 	0 },

{ "SENSORUART:FLOWCTL", 	_scpi_setSENSORUART_FLOWCTL, 	0 },
{ "SENSORUART:FLOWCTL?", 	_scpi_getSENSORUART_FLOWCTL, 	0 },
{ "SENSORUART:PARITY", 	_scpi_setSENSORUART_PARITY, 	0 },
{ "SENSORUART:PARITY?", 	_scpi_getSENSORUART_PARITY, 	0 },

{ "SENSORUART:STOPBIT", 	_scpi_setSENSORUART_STOPBIT, 	0 },
{ "SENSORUART:STOPBIT?", 	_scpi_getSENSORUART_STOPBIT, 	0 },
{ "SENSORUART:APPLYPARA", 	_scpi_setSENSORUART_APPLYPARA, 	0 },
{ "SENSORUART:STATE", 	_scpi_setSENSORUART_STATE, 	0 },

{ "SENSORUART:STATE?", 	_scpi_getSENSORUART_STATE, 	0 },
{ "SENSORUART:SOF", 	_scpi_setSENSORUART_SOF, 	0 },
{ "SENSORUART:SOF?", 	_scpi_getSENSORUART_SOF, 	0 },
{ "SENSORUART:FRAMELEN", 	_scpi_setSENSORUART_FRAMELEN, 	0 },

{ "SENSORUART:FRAMELEN?", 	_scpi_getSENSORUART_FRAMELEN, 	0 },
{ "SENSORUART:RECEIVENUM", 	_scpi_setSENSORUART_RECEIVENUM, 	0 },
{ "SENSORUART:RECEIVENUM?", 	_scpi_getSENSORUART_RECEIVENUM, 	0 },
{ "SENSORUART:SWITCHTIME", 	_scpi_setSENSORUART_SWITCHTIME, 	0 },

{ "SENSORUART:SWITCHTIME?", 	_scpi_getSENSORUART_SWITCHTIME, 	0 },
{ "SENSORUART:DATA?", 	_scpi_getSENSORUART_DATA, 	0 },
{ "PRESET:PVTCONFIG", 	_scpi_setPRESET_PVTCONFIG, 	0 },
{ "PRESET:PVTCONFIG?", 	_scpi_getPRESET_PVTCONFIG, 	0 },

{ "PRESET:POSITION", 	_scpi_setPRESET_POSITION, 	0 },
{ "PRESET:POSITION?", 	_scpi_getPRESET_POSITION, 	0 },
{ "PRESET:SPEED", 	_scpi_setPRESET_SPEED, 	0 },
{ "PRESET:SPEED?", 	_scpi_getPRESET_SPEED, 	0 },

{ "PRESET:TIME", 	_scpi_setPRESET_TIME, 	0 },
{ "PRESET:TIME?", 	_scpi_getPRESET_TIME, 	0 },
{ "PRESET:REMAINPOINT?", 	_scpi_getPRESET_REMAINPOINT, 	0 },
{ "PRESET:EXECUTE", 	_scpi_setPRESET_EXECUTE, 	0 },

{ "PRESET:STATE?", 	_scpi_getPRESET_STATE, 	0 },
{ "PRESET:ENDSTATE", 	_scpi_setPRESET_ENDSTATE, 	0 },
{ "PRESET:ENDSTATE?", 	_scpi_getPRESET_ENDSTATE, 	0 },
{ "PRESET:STOPMODE", 	_scpi_setPRESET_STOPMODE, 	0 },

{ "PRESET:STOPMODE?", 	_scpi_getPRESET_STOPMODE, 	0 },
{ "PRESET:STOPDISTANCE", 	_scpi_setPRESET_STOPDISTANCE, 	0 },
{ "PRESET:STOPDISTANCE?", 	_scpi_getPRESET_STOPDISTANCE, 	0 },
{ "ISOLATORIN:STATE", 	_scpi_setISOLATORIN_STATE, 	0 },

{ "ISOLATORIN:STATE?", 	_scpi_getISOLATORIN_STATE, 	0 },
{ "ISOLATORIN:TYPE", 	_scpi_setISOLATORIN_TYPE, 	0 },
{ "ISOLATORIN:TYPE?", 	_scpi_getISOLATORIN_TYPE, 	0 },
{ "ISOLATORIN:RESPONSE", 	_scpi_setISOLATORIN_RESPONSE, 	0 },

{ "ISOLATORIN:RESPONSE?", 	_scpi_getISOLATORIN_RESPONSE, 	0 },
{ "ISOLATORIN:RESPCHAN", 	_scpi_setISOLATORIN_RESPCHAN, 	0 },
{ "ISOLATORIN:RESPCHAN?", 	_scpi_getISOLATORIN_RESPCHAN, 	0 },
{ "ISOLATORIN:SMODE", 	_scpi_setISOLATORIN_SMODE, 	0 },

{ "ISOLATORIN:SMODE?", 	_scpi_getISOLATORIN_SMODE, 	0 },
{ "ISOLATORIN:SPERIOD", 	_scpi_setISOLATORIN_SPERIOD, 	0 },
{ "ISOLATORIN:SPERIOD?", 	_scpi_getISOLATORIN_SPERIOD, 	0 },
