{ "LINK:INTFC", 	_scpi_setLINK_INTFC, 	0 },
{ "LINK:INTFC?", 	_scpi_getLINK_INTFC, 	0 },
{ "LINK:DEVICEINFO?", 	_scpi_getLINK_DEVICEINFO, 	0 },
{ "SYSTEM:WORKMODE", 	_scpi_setSYSTEM_WORKMODE, 	0 },

{ "SYSTEM:WORKMODE?", 	_scpi_getSYSTEM_WORKMODE, 	0 },
{ "SYSTEM:POWERON", 	_scpi_setSYSTEM_POWERON, 	0 },
{ "SYSTEM:POWERON?", 	_scpi_getSYSTEM_POWERON, 	0 },
{ "SYSTEM:SN?", 	_scpi_getSYSTEM_SN, 	0 },

{ "SYSTEM:TYPE?", 	_scpi_getSYSTEM_TYPE, 	0 },
{ "SYSTEM:SOFTVER?", 	_scpi_getSYSTEM_SOFTVER, 	0 },
{ "SYSTEM:HARDVER?", 	_scpi_getSYSTEM_HARDVER, 	0 },
{ "SYSTEM:BOOTVER?", 	_scpi_getSYSTEM_BOOTVER, 	0 },

{ "SYSTEM:ERROR?", 	_scpi_getSYSTEM_ERROR, 	0 },
{ "SYSTEM:WARNCLEAR", 	_scpi_setSYSTEM_WARNCLEAR, 	0 },
{ "RS232:BAUD", 	_scpi_setRS232_BAUD, 	0 },
{ "RS232:BAUD?", 	_scpi_getRS232_BAUD, 	0 },

{ "RS232:WORDLEN", 	_scpi_setRS232_WORDLEN, 	0 },
{ "RS232:WORDLEN?", 	_scpi_getRS232_WORDLEN, 	0 },
{ "RS232:FLOWCTL", 	_scpi_setRS232_FLOWCTL, 	0 },
{ "RS232:FLOWCTL?", 	_scpi_getRS232_FLOWCTL, 	0 },

{ "RS232:PARITY", 	_scpi_setRS232_PARITY, 	0 },
{ "RS232:PARITY?", 	_scpi_getRS232_PARITY, 	0 },
{ "RS232:STOPBIT", 	_scpi_setRS232_STOPBIT, 	0 },
{ "RS232:STOPBIT?", 	_scpi_getRS232_STOPBIT, 	0 },

{ "RS232:APPLYPARA", 	_scpi_setRS232_APPLYPARA, 	0 },
{ "CAN:TYPE", 	_scpi_setCAN_TYPE, 	0 },
{ "CAN:TYPE?", 	_scpi_getCAN_TYPE, 	0 },
{ "CAN:BAUD", 	_scpi_setCAN_BAUD, 	0 },

{ "CAN:BAUD?", 	_scpi_getCAN_BAUD, 	0 },
{ "CAN:GROUP", 	_scpi_setCAN_GROUP, 	0 },
{ "CAN:GROUP?", 	_scpi_getCAN_GROUP, 	0 },
{ "CAN:SENDID", 	_scpi_setCAN_SENDID, 	0 },

{ "CAN:SENDID?", 	_scpi_getCAN_SENDID, 	0 },
{ "CAN:RECEIVEID", 	_scpi_setCAN_RECEIVEID, 	0 },
{ "CAN:RECEIVEID?", 	_scpi_getCAN_RECEIVEID, 	0 },
{ "CAN:GROUPID1", 	_scpi_setCAN_GROUPID1, 	0 },

{ "CAN:GROUPID1?", 	_scpi_getCAN_GROUPID1, 	0 },
{ "CAN:GROUPID2", 	_scpi_setCAN_GROUPID2, 	0 },
{ "CAN:GROUPID2?", 	_scpi_getCAN_GROUPID2, 	0 },
{ "CAN:BROADCASTID", 	_scpi_setCAN_BROADCASTID, 	0 },

{ "CAN:BROADCASTID?", 	_scpi_getCAN_BROADCASTID, 	0 },
{ "CAN:APPLYPARA", 	_scpi_setCAN_APPLYPARA, 	0 },
{ "CAN:NETMANAGELED", 	_scpi_setCAN_NETMANAGELED, 	0 },
{ "CAN:NETMANAGESTATE", 	_scpi_setCAN_NETMANAGESTATE, 	0 },

{ "CAN:NETMANAGESTATE?", 	_scpi_getCAN_NETMANAGESTATE, 	0 },
{ "CAN:NETMANAGEID", 	_scpi_setCAN_NETMANAGEID, 	0 },
{ "CAN:NETMANAGEID?", 	_scpi_getCAN_NETMANAGEID, 	0 },
{ "CAN:NETMANAGEHASH", 	_scpi_setCAN_NETMANAGEHASH, 	0 },

{ "CAN:NETMANAGEHASH?", 	_scpi_getCAN_NETMANAGEHASH, 	0 },
{ "CAN:NETMANAGESIGNATURE", 	_scpi_setCAN_NETMANAGESIGNATURE, 	0 },
{ "CAN:NETMANAGESIGNATURE?", 	_scpi_getCAN_NETMANAGESIGNATURE, 	0 },
{ "MOTION:SWITCH", 	_scpi_setMOTION_SWITCH, 	0 },

{ "MOTION:STATE?", 	_scpi_getMOTION_STATE, 	0 },
{ "MOTION:STATEREPORT", 	_scpi_setMOTION_STATEREPORT, 	0 },
{ "MOTION:STATEREPORT?", 	_scpi_getMOTION_STATEREPORT, 	0 },
{ "GLOBAL:GROUP", 	_scpi_setGLOBAL_GROUP, 	0 },

{ "GLOBAL:GROUP?", 	_scpi_getGLOBAL_GROUP, 	0 },
{ "GLOBAL:DISTINGUISH", 	_scpi_setGLOBAL_DISTINGUISH, 	0 },
{ "GLOBAL:DISTINGUISH?", 	_scpi_getGLOBAL_DISTINGUISH, 	0 },
{ "VALVECTRL:DEVICE", 	_scpi_setVALVECTRL_DEVICE, 	0 },

{ "VALVECTRL:DEVICE?", 	_scpi_getVALVECTRL_DEVICE, 	0 },
{ "VALVECTRL:PWMFREQ", 	_scpi_setVALVECTRL_PWMFREQ, 	0 },
{ "VALVECTRL:PWMFREQ?", 	_scpi_getVALVECTRL_PWMFREQ, 	0 },
{ "VALVECTRL:RTDUTY", 	_scpi_setVALVECTRL_RTDUTY, 	0 },

{ "VALVECTRL:RTDUTY?", 	_scpi_getVALVECTRL_RTDUTY, 	0 },
{ "VALVECTRL:ACTION", 	_scpi_setVALVECTRL_ACTION, 	0 },
{ "VALVECTRL:ACTION?", 	_scpi_getVALVECTRL_ACTION, 	0 },
{ "VALVECTRL:IDLEDUTY", 	_scpi_setVALVECTRL_IDLEDUTY, 	0 },

{ "VALVECTRL:IDLEDUTY?", 	_scpi_getVALVECTRL_IDLEDUTY, 	0 },
{ "VALVECTRL:HOLDDUTY", 	_scpi_setVALVECTRL_HOLDDUTY, 	0 },
{ "VALVECTRL:HOLDDUTY?", 	_scpi_getVALVECTRL_HOLDDUTY, 	0 },
{ "VALVECTRL:OPENDUTY", 	_scpi_setVALVECTRL_OPENDUTY, 	0 },

{ "VALVECTRL:OPENDUTY?", 	_scpi_getVALVECTRL_OPENDUTY, 	0 },
{ "VALVECTRL:OPENDLYTIME", 	_scpi_setVALVECTRL_OPENDLYTIME, 	0 },
{ "VALVECTRL:OPENDLYTIME?", 	_scpi_getVALVECTRL_OPENDLYTIME, 	0 },
{ "VALVECTRL:OPENTIME", 	_scpi_setVALVECTRL_OPENTIME, 	0 },

{ "VALVECTRL:OPENTIME?", 	_scpi_getVALVECTRL_OPENTIME, 	0 },
{ "VALVECTRL:RECORDSTATE", 	_scpi_setVALVECTRL_RECORDSTATE, 	0 },
{ "VALVECTRL:RECORDSTATE?", 	_scpi_getVALVECTRL_RECORDSTATE, 	0 },
{ "VALVECTRL:ONNUMS?", 	_scpi_getVALVECTRL_ONNUMS, 	0 },

{ "VALVECTRL:ONNUMSCLEAR", 	_scpi_setVALVECTRL_ONNUMSCLEAR, 	0 },
{ "VALVECTRL:OFFNUMS?", 	_scpi_getVALVECTRL_OFFNUMS, 	0 },
{ "VALVECTRL:OFFNUMSCLEAR", 	_scpi_setVALVECTRL_OFFNUMSCLEAR, 	0 },
{ "VALVECTRL:TIME?", 	_scpi_getVALVECTRL_TIME, 	0 },

{ "VALVECTRL:TIMECLEAR", 	_scpi_setVALVECTRL_TIMECLEAR, 	0 },
{ "THRESHOLD:HIGHPRESSURE", 	_scpi_setTHRESHOLD_HIGHPRESSURE, 	0 },
{ "THRESHOLD:HIGHPRESSURE?", 	_scpi_getTHRESHOLD_HIGHPRESSURE, 	0 },
{ "THRESHOLD:HIPRESSUREACTION", 	_scpi_setTHRESHOLD_HIPRESSUREACTION, 	0 },

{ "THRESHOLD:HIPRESSUREACTION?", 	_scpi_getTHRESHOLD_HIPRESSUREACTION, 	0 },
{ "THRESHOLD:LOWPRESSURE", 	_scpi_setTHRESHOLD_LOWPRESSURE, 	0 },
{ "THRESHOLD:LOWPRESSURE?", 	_scpi_getTHRESHOLD_LOWPRESSURE, 	0 },
{ "THRESHOLD:LOWPRESSUREACTION", 	_scpi_setTHRESHOLD_LOWPRESSUREACTION, 	0 },

{ "THRESHOLD:LOWPRESSUREACTION?", 	_scpi_getTHRESHOLD_LOWPRESSUREACTION, 	0 },
{ "THRESHOLD:HIGHCURRENT", 	_scpi_setTHRESHOLD_HIGHCURRENT, 	0 },
{ "THRESHOLD:HIGHCURRENT?", 	_scpi_getTHRESHOLD_HIGHCURRENT, 	0 },
{ "THRESHOLD:HICURRENTACTION", 	_scpi_setTHRESHOLD_HICURRENTACTION, 	0 },

{ "THRESHOLD:HICURRENTACTION?", 	_scpi_getTHRESHOLD_HICURRENTACTION, 	0 },
{ "THRESHOLD:LOWCURRENT", 	_scpi_setTHRESHOLD_LOWCURRENT, 	0 },
{ "THRESHOLD:LOWCURRENT?", 	_scpi_getTHRESHOLD_LOWCURRENT, 	0 },
{ "THRESHOLD:LOWCURRENTACTION", 	_scpi_setTHRESHOLD_LOWCURRENTACTION, 	0 },

{ "THRESHOLD:LOWCURRENTACTION?", 	_scpi_getTHRESHOLD_LOWCURRENTACTION, 	0 },
{ "THRESHOLD:ONNUMS", 	_scpi_setTHRESHOLD_ONNUMS, 	0 },
{ "THRESHOLD:ONNUMS?", 	_scpi_getTHRESHOLD_ONNUMS, 	0 },
{ "THRESHOLD:NUMSACTION", 	_scpi_setTHRESHOLD_NUMSACTION, 	0 },

{ "THRESHOLD:NUMSACTION?", 	_scpi_getTHRESHOLD_NUMSACTION, 	0 },
{ "THRESHOLD:TIME", 	_scpi_setTHRESHOLD_TIME, 	0 },
{ "THRESHOLD:TIME?", 	_scpi_getTHRESHOLD_TIME, 	0 },
{ "THRESHOLD:TIMEACTION", 	_scpi_setTHRESHOLD_TIMEACTION, 	0 },

{ "THRESHOLD:TIMEACTION?", 	_scpi_getTHRESHOLD_TIMEACTION, 	0 },
{ "PVT:EXECMODE", 	_scpi_setPVT_EXECMODE, 	0 },
{ "PVT:EXECMODE?", 	_scpi_getPVT_EXECMODE, 	0 },
{ "PVT:RESET", 	_scpi_setPVT_RESET, 	0 },

{ "PVT:CYCLES", 	_scpi_setPVT_CYCLES, 	0 },
{ "PVT:CYCLES?", 	_scpi_getPVT_CYCLES, 	0 },
{ "PVT:GRADE", 	_scpi_setPVT_GRADE, 	0 },
{ "PVT:GRADE?", 	_scpi_getPVT_GRADE, 	0 },

{ "PVT:BUFFERCHECK?", 	_scpi_getPVT_BUFFERCHECK, 	0 },
{ "PVT:START", 	_scpi_setPVT_START, 	0 },
{ "PVT:START?", 	_scpi_getPVT_START, 	0 },
{ "PVT:END", 	_scpi_setPVT_END, 	0 },

{ "PVT:END?", 	_scpi_getPVT_END, 	0 },
{ "PVT:PDATA", 	_scpi_setPVT_PDATA, 	0 },
{ "PVT:PDATA?", 	_scpi_getPVT_PDATA, 	0 },
{ "PVT:TDATA", 	_scpi_setPVT_TDATA, 	0 },

{ "PVT:TDATA?", 	_scpi_getPVT_TDATA, 	0 },
{ "PVT:HOLD", 	_scpi_setPVT_HOLD, 	0 },
{ "PVT:HOLD?", 	_scpi_getPVT_HOLD, 	0 },
{ "PVT:SAVE", 	_scpi_setPVT_SAVE, 	0 },

{ "PVT:SAVE?", 	_scpi_getPVT_SAVE, 	0 },
{ "CALIBRATION:TYPE", 	_scpi_setCALIBRATION_TYPE, 	0 },
{ "CALIBRATION:TYPE?", 	_scpi_getCALIBRATION_TYPE, 	0 },
{ "CALIBRATION:SAMPLERATE", 	_scpi_setCALIBRATION_SAMPLERATE, 	0 },

{ "CALIBRATION:SAMPLERATE?", 	_scpi_getCALIBRATION_SAMPLERATE, 	0 },
{ "CALIBRATION:OPENTIME", 	_scpi_setCALIBRATION_OPENTIME, 	0 },
{ "CALIBRATION:OPENTIME?", 	_scpi_getCALIBRATION_OPENTIME, 	0 },
{ "CALIBRATION:HOLDTIME", 	_scpi_setCALIBRATION_HOLDTIME, 	0 },

{ "CALIBRATION:HOLDTIME?", 	_scpi_getCALIBRATION_HOLDTIME, 	0 },
{ "CALIBRATION:CLOSETIME", 	_scpi_setCALIBRATION_CLOSETIME, 	0 },
{ "CALIBRATION:CLOSETIME?", 	_scpi_getCALIBRATION_CLOSETIME, 	0 },
{ "CALIBRATION:OPENDUTY", 	_scpi_setCALIBRATION_OPENDUTY, 	0 },

{ "CALIBRATION:OPENDUTY?", 	_scpi_getCALIBRATION_OPENDUTY, 	0 },
{ "CALIBRATION:HOLDDUTY", 	_scpi_setCALIBRATION_HOLDDUTY, 	0 },
{ "CALIBRATION:HOLDDUTY?", 	_scpi_getCALIBRATION_HOLDDUTY, 	0 },
{ "CALIBRATION:DATALENGTH?", 	_scpi_getCALIBRATION_DATALENGTH, 	0 },

{ "CALIBRATION:DATAUPCTRL", 	_scpi_setCALIBRATION_DATAUPCTRL, 	0 },
{ "CALIBRATION:DATAUP", 	_scpi_setCALIBRATION_DATAUP, 	0 },
{ "REPORT:STATE", 	_scpi_setREPORT_STATE, 	0 },
{ "REPORT:STATE?", 	_scpi_getREPORT_STATE, 	0 },

{ "REPORT:PERIOD", 	_scpi_setREPORT_PERIOD, 	0 },
{ "REPORT:PERIOD?", 	_scpi_getREPORT_PERIOD, 	0 },
{ "REPORT:DATA?", 	_scpi_getREPORT_DATA, 	0 },
{ "IOCONFIG:IOFUNCSEL", 	_scpi_setIOCONFIG_IOFUNCSEL, 	0 },

{ "IOCONFIG:IOFUNCSEL?", 	_scpi_getIOCONFIG_IOFUNCSEL, 	0 },
{ "IOCONFIG:SWFILTERDELAY", 	_scpi_setIOCONFIG_SWFILTERDELAY, 	0 },
{ "IOCONFIG:SWFILTERDELAY?", 	_scpi_getIOCONFIG_SWFILTERDELAY, 	0 },
{ "IOCONFIG:SWFILTERCOUNTER", 	_scpi_setIOCONFIG_SWFILTERCOUNTER, 	0 },

{ "IOCONFIG:SWFILTERCOUNTER?", 	_scpi_getIOCONFIG_SWFILTERCOUNTER, 	0 },
{ "IOCONFIG:TRIGEDGE", 	_scpi_setIOCONFIG_TRIGEDGE, 	0 },
{ "IOCONFIG:TRIGEDGE?", 	_scpi_getIOCONFIG_TRIGEDGE, 	0 },
{ "IOCONFIG:BAUD", 	_scpi_setIOCONFIG_BAUD, 	0 },

{ "IOCONFIG:BAUD?", 	_scpi_getIOCONFIG_BAUD, 	0 },
{ "IOCONFIG:WORDLEN", 	_scpi_setIOCONFIG_WORDLEN, 	0 },
{ "IOCONFIG:WORDLEN?", 	_scpi_getIOCONFIG_WORDLEN, 	0 },
{ "IOCONFIG:FLOWCTL", 	_scpi_setIOCONFIG_FLOWCTL, 	0 },

{ "IOCONFIG:FLOWCTL?", 	_scpi_getIOCONFIG_FLOWCTL, 	0 },
{ "IOCONFIG:PARITY", 	_scpi_setIOCONFIG_PARITY, 	0 },
{ "IOCONFIG:PARITY?", 	_scpi_getIOCONFIG_PARITY, 	0 },
{ "IOCONFIG:STOPBIT", 	_scpi_setIOCONFIG_STOPBIT, 	0 },

{ "IOCONFIG:STOPBIT?", 	_scpi_getIOCONFIG_STOPBIT, 	0 },
{ "IOCONFIG:APPLYPARA", 	_scpi_setIOCONFIG_APPLYPARA, 	0 },
